Merging upstream version 0.6.5.

diff --git a/src/server/Makefile.in b/src/server/Makefile.in
--- a/src/server/Makefile.in
+++ b/src/server/Makefile.in
@@ -14,7 +14,7 @@
 
 @SET_MAKE@
 
-SOURCES = $(gnunet_peer_info_SOURCES) $(gnunet_transport_check_SOURCES) $(gnunet_update_SOURCES) $(gnunetd_SOURCES)
+SOURCES = $(fragmentationtest_SOURCES) $(gnunet_peer_info_SOURCES) $(gnunet_transport_check_SOURCES) $(gnunet_update_SOURCES) $(gnunetd_SOURCES)
 
 srcdir = @srcdir@
 top_srcdir = @top_srcdir@
@@ -39,6 +39,7 @@ POST_UNINSTALL = :
 host_triplet = @host@
 bin_PROGRAMS = gnunetd$(EXEEXT) gnunet-update$(EXEEXT) \
 	gnunet-peer-info$(EXEEXT) gnunet-transport-check$(EXEEXT)
+check_PROGRAMS = fragmentationtest$(EXEEXT)
 subdir = src/server
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
@@ -57,6 +58,10 @@ CONFIG_CLEAN_FILES =
 am__installdirs = "$(DESTDIR)$(bindir)"
 binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
 PROGRAMS = $(bin_PROGRAMS)
+am_fragmentationtest_OBJECTS = fragmentationtest.$(OBJEXT)
+fragmentationtest_OBJECTS = $(am_fragmentationtest_OBJECTS)
+fragmentationtest_DEPENDENCIES =  \
+	$(top_builddir)/src/util/libgnunetutil.la
 am_gnunet_peer_info_OBJECTS = gnunet-peer-info.$(OBJEXT) \
 	keyservice.$(OBJEXT) knownhosts.$(OBJEXT) transport.$(OBJEXT)
 gnunet_peer_info_OBJECTS = $(am_gnunet_peer_info_OBJECTS)
@@ -73,16 +78,19 @@ gnunet_update_OBJECTS = $(am_gnunet_update_OBJECTS)
 gnunet_update_DEPENDENCIES =  \
 	$(top_builddir)/src/util/libgnunetutil.la
 am_gnunetd_OBJECTS = connection.$(OBJEXT) core.$(OBJEXT) \
-	gnunetd.$(OBJEXT) handler.$(OBJEXT) heloexchange.$(OBJEXT) \
-	keyservice.$(OBJEXT) knownhosts.$(OBJEXT) pingpong.$(OBJEXT) \
-	policy.$(OBJEXT) startup.$(OBJEXT) tcpserver.$(OBJEXT) \
-	traffic.$(OBJEXT) transport.$(OBJEXT) httphelo.$(OBJEXT)
+	fragmentation.$(OBJEXT) gnunetd.$(OBJEXT) handler.$(OBJEXT) \
+	heloexchange.$(OBJEXT) keyservice.$(OBJEXT) \
+	knownhosts.$(OBJEXT) pingpong.$(OBJEXT) policy.$(OBJEXT) \
+	startup.$(OBJEXT) tcpserver.$(OBJEXT) traffic.$(OBJEXT) \
+	transport.$(OBJEXT) httphelo.$(OBJEXT)
 gnunetd_OBJECTS = $(am_gnunetd_OBJECTS)
 gnunetd_DEPENDENCIES = $(top_builddir)/src/util/libgnunetutil.la
 DEFAULT_INCLUDES = -I. -I$(srcdir) -I$(top_builddir)
 depcomp = $(SHELL) $(top_srcdir)/depcomp
 am__depfiles_maybe = depfiles
 @AMDEP_TRUE@DEP_FILES = ./$(DEPDIR)/connection.Po ./$(DEPDIR)/core.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/fragmentation.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/fragmentationtest.Po \
 @AMDEP_TRUE@	./$(DEPDIR)/gnunet-peer-info.Po \
 @AMDEP_TRUE@	./$(DEPDIR)/gnunet-transport-check.Po \
 @AMDEP_TRUE@	./$(DEPDIR)/gnunet-update.Po \
@@ -101,12 +109,12 @@ LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) \
 CCLD = $(CC)
 LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
 	$(AM_LDFLAGS) $(LDFLAGS) -o $@
-SOURCES = $(gnunet_peer_info_SOURCES) \
+SOURCES = $(fragmentationtest_SOURCES) $(gnunet_peer_info_SOURCES) \
 	$(gnunet_transport_check_SOURCES) $(gnunet_update_SOURCES) \
 	$(gnunetd_SOURCES)
-DIST_SOURCES = $(gnunet_peer_info_SOURCES) \
-	$(gnunet_transport_check_SOURCES) $(gnunet_update_SOURCES) \
-	$(gnunetd_SOURCES)
+DIST_SOURCES = $(fragmentationtest_SOURCES) \
+	$(gnunet_peer_info_SOURCES) $(gnunet_transport_check_SOURCES) \
+	$(gnunet_update_SOURCES) $(gnunetd_SOURCES)
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
@@ -171,6 +179,8 @@ HAVE_IPV6_FALSE = @HAVE_IPV6_FALSE@
 HAVE_IPV6_TRUE = @HAVE_IPV6_TRUE@
 HAVE_MYSQL_FALSE = @HAVE_MYSQL_FALSE@
 HAVE_MYSQL_TRUE = @HAVE_MYSQL_TRUE@
+HAVE_SQLITE_FALSE = @HAVE_SQLITE_FALSE@
+HAVE_SQLITE_TRUE = @HAVE_SQLITE_TRUE@
 HAVE_TDB_FALSE = @HAVE_TDB_FALSE@
 HAVE_TDB_TRUE = @HAVE_TDB_TRUE@
 HAVE_ZLIB_FALSE = @HAVE_ZLIB_FALSE@
@@ -280,6 +290,7 @@ INCLUDES = -I$(top_srcdir)/src/include
 gnunetd_SOURCES = \
  connection.c \
  core.c \
+ fragmentation.c \
  gnunetd.c \
  handler.c  \
  heloexchange.c  \
@@ -293,6 +304,7 @@ gnunetd_SOURCES = \
  transport.c \
  connection.h \
  core.h \
+ fragmentation.h \
  handler.h \
  heloexchange.h \
  keyservice.h \
@@ -337,6 +349,13 @@ gnunet_peer_info_SOURCES = \
 
 gnunet_peer_info_LDADD = \
  $(top_builddir)/src/util/libgnunetutil.la
+
+TESTS = $(check_PROGRAMS)
+fragmentationtest_SOURCES = \
+ fragmentationtest.c 
+
+fragmentationtest_LDADD = \
+ $(top_builddir)/src/util/libgnunetutil.la  
 
 all: all-am
 
@@ -399,6 +418,16 @@ clean-binPROGRAMS:
 	  echo " rm -f $$p $$f"; \
 	  rm -f $$p $$f ; \
 	done
+
+clean-checkPROGRAMS:
+	@list='$(check_PROGRAMS)'; for p in $$list; do \
+	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
+	  echo " rm -f $$p $$f"; \
+	  rm -f $$p $$f ; \
+	done
+fragmentationtest$(EXEEXT): $(fragmentationtest_OBJECTS) $(fragmentationtest_DEPENDENCIES) 
+	@rm -f fragmentationtest$(EXEEXT)
+	$(LINK) $(fragmentationtest_LDFLAGS) $(fragmentationtest_OBJECTS) $(fragmentationtest_LDADD) $(LIBS)
 gnunet-peer-info$(EXEEXT): $(gnunet_peer_info_OBJECTS) $(gnunet_peer_info_DEPENDENCIES) 
 	@rm -f gnunet-peer-info$(EXEEXT)
 	$(LINK) $(gnunet_peer_info_LDFLAGS) $(gnunet_peer_info_OBJECTS) $(gnunet_peer_info_LDADD) $(LIBS)
@@ -420,6 +449,8 @@ distclean-compile:
 
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/connection.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/core.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/fragmentation.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/fragmentationtest.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/gnunet-peer-info.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/gnunet-transport-check.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/gnunet-update.Po@am__quote@
@@ -518,6 +549,79 @@ GTAGS:
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    skipped="($$skip tests were not run)"; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
+
 distdir: $(DISTFILES)
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
@@ -546,6 +650,8 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 all-am: Makefile $(PROGRAMS)
 installdirs:
@@ -578,7 +684,8 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am
+clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
+	clean-libtool mostlyclean-am
 
 distclean: distclean-am
 	-rm -rf ./$(DEPDIR)
@@ -626,8 +733,9 @@ ps-am:
 
 uninstall-am: uninstall-binPROGRAMS uninstall-info-am
 
-.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
-	clean-generic clean-libtool ctags distclean distclean-compile \
+.PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
+	clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
+	clean-libtool ctags distclean distclean-compile \
 	distclean-generic distclean-libtool distclean-tags distdir dvi \
 	dvi-am html html-am info info-am install install-am \
 	install-binPROGRAMS install-data install-data-am install-exec \
