Adding debian version 0.6.4-1.

diff --git a/debian/gnunet.postinst b/debian/gnunet.postinst
--- a/debian/gnunet.postinst
+++ b/debian/gnunet.postinst
@@ -1,7 +1,46 @@
-#!/bin/sh
+#! /bin/sh
+# postinst script for gnunet
+#
+# see: dh_installdeb(1)
 
-# This is need to migrate data from 0.6.1b or later 
-echo "Migrating previous GNUnet data (gnunet-check -u)"
-gnunet-check -u
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+
+case "$1" in
+    configure)
+    	# This is need to migrate data from 0.6.1b or later
+	# (changed to -a since AFS-Quota changed from 0.6.4
+	echo "Migrating previous GNUnet data (gnunet-check -a)"
+	gnunet-check -a
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
+
+
